baseURL = "https://nagimemooo.github.io"
languageCode = "zh-Hans"
defaultContentLanguage = "tc"
title = "nagimemooo 筆記"
theme = "dream"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/img/chihiro1.jpg"
  linkColor = "seagreen"

  author = "nagi"
  description = "nagi 沙發馬鈴薯 少女 "
  avatar = "/img/docker.jpg"
  motto = "列表式顯示請點下列icon。"
  
  email = "nagimemooo@gmail.com"